//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortysDLP_dotNet_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DOWNLOADPATH {
            get {
                return ((string)(this["DOWNLOADPATH"]));
            }
            set {
                this["DOWNLOADPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZEITSPANNE_VON {
            get {
                return ((string)(this["ZEITSPANNE_VON"]));
            }
            set {
                this["ZEITSPANNE_VON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZEITSPANNE_BIS {
            get {
                return ((string)(this["ZEITSPANNE_BIS"]));
            }
            set {
                this["ZEITSPANNE_BIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ERSTESEKUNDEN_SEKUNDEN {
            get {
                return ((string)(this["ERSTESEKUNDEN_SEKUNDEN"]));
            }
            set {
                this["ERSTESEKUNDEN_SEKUNDEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHECKED_VIDEOFORMAT {
            get {
                return ((string)(this["CHECKED_VIDEOFORMAT"]));
            }
            set {
                this["CHECKED_VIDEOFORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHECKED_ZEITSPANNE {
            get {
                return ((string)(this["CHECKED_ZEITSPANNE"]));
            }
            set {
                this["CHECKED_ZEITSPANNE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHECKED_ERSTESEKUNDEN {
            get {
                return ((string)(this["CHECKED_ERSTESEKUNDEN"]));
            }
            set {
                this["CHECKED_ERSTESEKUNDEN"] = value;
            }
        }
    }
}
