//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortysDLP_dotNet_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DOWNLOADPATH {
            get {
                return ((string)(this["DOWNLOADPATH"]));
            }
            set {
                this["DOWNLOADPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZEITSPANNE_VON {
            get {
                return ((string)(this["ZEITSPANNE_VON"]));
            }
            set {
                this["ZEITSPANNE_VON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZEITSPANNE_BIS {
            get {
                return ((string)(this["ZEITSPANNE_BIS"]));
            }
            set {
                this["ZEITSPANNE_BIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ERSTESEKUNDEN_SEKUNDEN {
            get {
                return ((string)(this["ERSTESEKUNDEN_SEKUNDEN"]));
            }
            set {
                this["ERSTESEKUNDEN_SEKUNDEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHECKED_VIDEOFORMAT {
            get {
                return ((string)(this["CHECKED_VIDEOFORMAT"]));
            }
            set {
                this["CHECKED_VIDEOFORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHECKED_ZEITSPANNE {
            get {
                return ((string)(this["CHECKED_ZEITSPANNE"]));
            }
            set {
                this["CHECKED_ZEITSPANNE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHECKED_ERSTESEKUNDEN {
            get {
                return ((string)(this["CHECKED_ERSTESEKUNDEN"]));
            }
            set {
                this["CHECKED_ERSTESEKUNDEN"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/yt-dlp/yt-dlp/releases/latest")]
        public string YT_DLP_RELEASE_URL {
            get {
                return ((string)(this["YT_DLP_RELEASE_URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/GyanD/codexffmpeg/releases/latest")]
        public string FFMPEG_RELEASE_URL {
            get {
                return ((string)(this["FFMPEG_RELEASE_URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ressources/ffmpeg/ffmpeg.json")]
        public string FFMPEG_JSON_PATH {
            get {
                return ((string)(this["FFMPEG_JSON_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ressources/yt-dlp/ffmpeg.exe")]
        public string FFMPEG_PATH {
            get {
                return ((string)(this["FFMPEG_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ressources/yt-dlp/ffprobe.exe")]
        public string FFPROBE_PATH {
            get {
                return ((string)(this["FFPROBE_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ressources/ffmpeg/ffmpeg_download.zip")]
        public string TEMP_FFMPEG_DOWNLOAD_PATH {
            get {
                return ((string)(this["TEMP_FFMPEG_DOWNLOAD_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ressources/yt-dlp/yt-dlp.exe")]
        public string YT_DLP_PATH {
            get {
                return ((string)(this["YT_DLP_PATH"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CHECKED_AUDIO_ONLY {
            get {
                return ((string)(this["CHECKED_AUDIO_ONLY"]));
            }
            set {
                this["CHECKED_AUDIO_ONLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SELECTED_AUDIO_FORMAT {
            get {
                return ((string)(this["SELECTED_AUDIO_FORMAT"]));
            }
            set {
                this["SELECTED_AUDIO_FORMAT"] = value;
            }
        }
    }
}
